# Generated by Django 4.0.10 on 2024-06-28 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(blank=True, max_length=255, verbose_name='Type de Mouvement')),
                ('quantite', models.IntegerField(blank=True, null=True, verbose_name='Quantite')),
                ('motif', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Motif')),
                ('visible', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Article.stockarticle', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
            },
        ),
    ]
