# Generated by Django 4.0.10 on 2024-06-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mouvement', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouvement',
            old_name='article',
            new_name='id_article',
        ),
        migrations.RenameField(
            model_name='mouvement',
            old_name='user',
            new_name='id_user',
        ),
    ]
