# Generated by Django 4.0.10 on 2024-06-28 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(blank=True, max_length=255, verbose_name='Categorie')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='StockArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=255, verbose_name='Libelle')),
                ('quantite', models.IntegerField(blank=True, default=0, verbose_name='Quantite')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('id_categorie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Article.categoriearticle', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
